apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dkr.ecr.eu-north-1.amazonaws.com/chocolate-bravo-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: redis-secret
        volumeMounts:
        - name: backend-storage
          mountPath: /app/uploads
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-pvc