apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf   # Mount the specific file from ConfigMap
        - name: ssl-cert
          mountPath: /etc/nginx/ssl
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: ssl-cert
        secret:
          secretName: tls-secret
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc
