apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http        # Add this
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https       # Add this
      protocol: TCP
      port: 443
      targetPort: 443
