apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2        # <--- add this line
  resources:
    requests:
      storage: 1Gi
